//Se debe crear una función auto invocable (dos pares de parentesis) el primero recibe un callback...
//...que es la función que se va a ejecutar, adentro de la función la lógica será la siguiente (es...
//...menester loguearnos la primera vez exitosamente para poder guardar bien esas credenciales...
//...autenticadas en el localstorage)

(() => {
  //obtenemos la llave del user con la que lo guardamos en el localstorage al loguearse
  const user = localStorage.getItem("user");
  //si no hubo un usuario quiere decir que no está autenticado y no tiene permisos...
  //...entonces redirijalo al login
  if (!user) {
    window.location.href = "login.html";
  }
  //El authGuard debo importarlo en la cabecera del archivo que quiero proteger...
  //...para este caso será el del administrator.html
  //Para corroborar, si yo me logueo exitosamente y después copio y pego el link del admin en otra ventana...
  //...me dejará entrar debido a que las credenciales están guardadas en el localstorage, pero si elimino...
  //...la info del localstorage, y repito el proceso, no me dejará entrar porque no hay info en localstorage,...
  //...como en este caso las categorias y las noticias están en la misma vista también están protegidas.
})();
